// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYto_LpQn-nN-w3TQtz9tMlv0sSyrXeus',
    appId: '1:652287221531:android:5a1581f9682749c9083dbe',
    messagingSenderId: '652287221531',
    projectId: 'megamart-3dfd1',
    storageBucket: 'megamart-3dfd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXLKIE5WRzWfiXj37dwAn_HafiRCenK5o',
    appId: '1:652287221531:ios:2040539c568f4349083dbe',
    messagingSenderId: '652287221531',
    projectId: 'megamart-3dfd1',
    storageBucket: 'megamart-3dfd1.firebasestorage.app',
    iosBundleId: 'com.example.megamart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXLKIE5WRzWfiXj37dwAn_HafiRCenK5o',
    appId: '1:652287221531:ios:2040539c568f4349083dbe',
    messagingSenderId: '652287221531',
    projectId: 'megamart-3dfd1',
    storageBucket: 'megamart-3dfd1.firebasestorage.app',
    iosBundleId: 'com.example.megamart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARt94tUkr6ECTzuAu-Q6F3leInAg4DlIM',
    appId: '1:652287221531:web:9906c516cf74e590083dbe',
    messagingSenderId: '652287221531',
    projectId: 'megamart-3dfd1',
    authDomain: 'megamart-3dfd1.firebaseapp.com',
    storageBucket: 'megamart-3dfd1.firebasestorage.app',
    measurementId: 'G-0J4913WTCT',
  );
}
